### ISSUE TITLE
Tutorial breaking (raising torch error)

### ISSUE THREAD

**Issue by raverdude** [broadinstitute/CellBender#104]
I was able to successfully install but ran into error when running the test data set included in CellBender.

```
(CellBender) raverdude@nc010:~/CellBender/examples/remove_background % python generate_tiny_10x_pbmc.py
Extracting pbmc4k (CellRanger 2.1.0, v2 Chemistry)...
Loading the gene expression matrix...
Loading genes and barcodes...
Trimming pbmc4k (CellRanger 2.1.0, v2 Chemistry)...
Number of genes in the trimmed dataset: 100
Number of barcodes in the trimmed dataset: 14650
Expected number of cells in the trimmed dataset: 500
Saving the trimmed dataset...
Cleaning up...
Done!
(CellBender) raverdude@nc010:~/CellBender/examples/remove_background % cellbender remove-background \
>      --input ./tiny_raw_gene_bc_matrices/GRCh38 \
>      --output ./tiny_10x_pbmc.h5 \
>      --expected-cells 500 \
>      --total-droplets-included 5000
cellbender:remove-background: Command:
cellbender remove-background --input ./tiny_raw_gene_bc_matrices/GRCh38 --output ./tiny_10x_pbmc.h5 --expected-cells 500 --total-droplets-included 5000
cellbender:remove-background: 2021-06-15 15:05:37
cellbender:remove-background: Running remove-background
cellbender:remove-background: Loading data from directory ./tiny_raw_gene_bc_matrices/GRCh38
cellbender:remove-background: CellRanger v2 format
cellbender:remove-background: Trimming dataset for inference.
cellbender:remove-background: Including 100 genes that have nonzero counts.
cellbender:remove-background: Prior on counts in empty droplets is 53
cellbender:remove-background: Prior on counts for cells is 8830
cellbender:remove-background: Excluding barcodes with counts below 26
cellbender:remove-background: Using 500 probable cell barcodes, plus an additional 4500 barcodes, and 796 empty droplets.
cellbender:remove-background: Largest surely-empty droplet has 36 UMI counts.
cellbender:remove-background: Running inference...
Traceback (most recent call last):
  File "/user/miniconda3/envs/CellBender/bin/cellbender", line 33, in <module>
    sys.exit(load_entry_point('cellbender', 'console_scripts', 'cellbender')())
  File "/user/CellBender/cellbender/base_cli.py", line 101, in main
    cli_dict[args.tool].run(args)
  File "/user/CellBender/cellbender/remove_background/cli.py", line 109, in run
    main(args)
  File "/user/CellBender/cellbender/remove_background/cli.py", line 204, in main
    run_remove_background(args)
  File "/user/CellBender/cellbender/remove_background/cli.py", line 166, in run_remove_background
    inferred_model = run_inference(dataset_obj, args)
  File "/user/CellBender/cellbender/remove_background/train.py", line 319, in run_inference
    epoch_elbo_fail_fraction=args.epoch_elbo_fail_fraction)
  File "/user/miniconda3/envs/CellBender/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/user/CellBender/cellbender/remove_background/train.py", line 144, in run_training
    total_epoch_loss_train = train_epoch(svi, train_loader)
  File "/user/CellBender/cellbender/remove_background/train.py", line 55, in train_epoch
    epoch_loss += svi.step(x_cell_batch)
  File "/user/.local/lib/python3.7/site-packages/pyro/infer/svi.py", line 128, in step
    loss = self.loss_and_grads(self.model, self.guide, *args, **kwargs)
  File "/user/.local/lib/python3.7/site-packages/pyro/infer/traceenum_elbo.py", line 405, in loss_and_grads
    elbo_particle = _compute_dice_elbo(model_trace, guide_trace)
  File "/user/.local/lib/python3.7/site-packages/pyro/infer/traceenum_elbo.py", line 185, in _compute_dice_elbo
    return Dice(guide_trace, ordering).compute_expectation(costs)
  File "/user/.local/lib/python3.7/site-packages/pyro/infer/util.py", line 303, in compute_expectation
    expected_cost = expected_cost + scale * torch.tensordot(prob, cost, prob.dim())
  File "/user/miniconda3/envs/CellBender/lib/python3.7/site-packages/torch/functional.py", line 929, in tensordot
    raise RuntimeError(f"unsupported input to tensordot, got dims={dims}")
RuntimeError: unsupported input to tensordot, got dims=0
(CellBender) raverdude@nc010:~/CellBender/examples/remove_background % ls
generate_tiny_10x_pbmc.py  tiny_10x_pbmc.log  tiny_raw_gene_bc_matrices
(CellBender) raverdude@nc010:~/CellBender/examples/remove_background %
```

Here are my loaded packages
```
(CellBender) raverdude@nc010:~/CellBender/examples/remove_background % pip list
Package                       Version             Location
----------------------------- ------------------- --------------------------------
alabaster                     0.7.12
anndata                       0.7.6
Babel                         2.9.1
cached-property               1.5.2
cellbender                    0.2.0               /user/CellBender
certifi                       2021.5.30
chardet                       4.0.0
cycler                        0.10.0
docutils                      0.16
h5py                          3.2.1
idna                          2.10
imagesize                     1.2.0
importlib-metadata            4.5.0
Jinja2                        3.0.1
joblib                        1.0.1
kiwisolver                    1.3.1
MarkupSafe                    2.0.1
matplotlib                    3.4.2
mkl-fft                       1.3.0
mkl-random                    1.2.1
mkl-service                   2.3.0
mock                          4.0.2
natsort                       7.1.1
numexpr                       2.7.3
numpy                         1.20.3
olefile                       0.46
opt-einsum                    3.3.0
packaging                     20.9
pandas                        1.2.4
Pillow                        8.2.0
pip                           21.1.2
Pygments                      2.9.0
pyparsing                     2.4.7
pyro-api                      0.1.2
pyro-ppl                      1.6.0
python-dateutil               2.8.1
pytz                          2021.1
requests                      2.25.1
scikit-learn                  0.24.2
scipy                         1.6.3
setuptools                    52.0.0.post20210125
six                           1.16.0
snowballstemmer               2.1.0
Sphinx                        4.0.2
sphinx-argparse               0.2.5
sphinx-autodoc-typehints      1.12.0
sphinx-rtd-theme              0.5.2
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-programoutput   0.17
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
tables                        3.6.1
threadpoolctl                 2.1.0
torch                         1.9.0
torchvision                   0.10.0
tqdm                          4.61.0
typing-extensions             3.7.4.3
urllib3                       1.26.5
wheel                         0.36.2
xlrd                          1.2.0
zipp                          3.4.1
```

**Comment by raverdude** [comment]
fixed by downgrading torch: `conda install pytorch==1.8.0 torchvision==0.9.0 torchaudio==0.8.0 -c pytorch`
