### ISSUE TITLE
ImportError: DLL load failed while importing defs: The specified procedure could not be found.

### ISSUE THREAD

**Issue by jevaremdphd** [broadinstitute/CellBender#148]
I'm new to CellBender. When I run the remove-background command, I keep on getting this error:

Traceback (most recent call last):
  File "C:\Users\reyesje\.conda\envs\cellbender\Scripts\cellbender-script.py", line 33, in <module>
    sys.exit(load_entry_point('cellbender', 'console_scripts', 'cellbender')())
  File "c:\cellbender\cellbender\base_cli.py", line 91, in main
    cli_dict = generate_cli_dictionary()
  File "c:\cellbender\cellbender\base_cli.py", line 52, in generate_cli_dictionary
    module_cli = importlib.import_module('.'.join(module_cli_str_list))
  File "C:\Users\reyesje\.conda\envs\cellbender\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "c:\cellbender\cellbender\remove_background\cli.py", line 4, in <module>
    from cellbender.remove_background.data.dataset import SingleCellRNACountsDataset
  File "c:\cellbender\cellbender\remove_background\data\dataset.py", line 10, in <module>
    import anndata
  File "C:\Users\reyesje\.conda\envs\cellbender\lib\site-packages\anndata\__init__.py", line 7, in <module>
    from ._core.anndata import AnnData
  File "C:\Users\reyesje\.conda\envs\cellbender\lib\site-packages\anndata\_core\anndata.py", line 17, in <module>
    import h5py
  File "C:\Users\reyesje\.conda\envs\cellbender\lib\site-packages\h5py\__init__.py", line 33, in <module>
    from . import version
  File "C:\Users\reyesje\.conda\envs\cellbender\lib\site-packages\h5py\version.py", line 15, in <module>
    from . import h5 as _h5
  File "h5py\h5.pyx", line 1, in init h5py.h5
**ImportError: DLL load failed while importing defs: The specified procedure could not be found.**

Can someone help me with this?

**Comment by sjfleming** [comment]
I am not sure what this is about!  Hoping someone else can chime in with advice if they have seen it.

**Comment by sjfleming** [comment]
I gather you are working on a windows machine, right?  And it looks like you installed cellbender to a conda environment.  That looks good.

It might be something to do with h5py in windows.

Maybe this could help?
https://stackoverflow.com/questions/45046796/importerror-dll-load-failedimport-h5py

**Comment by sjfleming** [comment]
Were you able to resolve this @areyoukidneyme ?
