### ISSUE TITLE
Error importlib-metadata package

### ISSUE THREAD

**Issue by ccruizm** [broadinstitute/CellBender#164]
Good day,

I have tried to run cellbender but I am encountering the next error:
```
Traceback (most recent call last):
  File "/hpc/pmc_stunnenberg/cruiz/miniconda3/envs/cellbender/bin/cellbender", line 33, in <module>
    sys.exit(load_entry_point('cellbender', 'console_scripts', 'cellbender')())
  File "/hpc/pmc_stunnenberg/cruiz/miniconda3/envs/cellbender/bin/cellbender", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/hpc/pmc_stunnenberg/cruiz/miniconda3/envs/cellbender/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 988, in distribution
    return Distribution.from_name(distribution_name)
  File "/hpc/pmc_stunnenberg/cruiz/miniconda3/envs/cellbender/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 566, in from_name
    raise PackageNotFoundError(name)
importlib_metadata.PackageNotFoundError: No package metadata was found for cellbender
```
I have installed cell bender according to the instructions in a new conda environment. If import the library in python it works but cellbender does not find it. I have installed` importlib-metadata` via pip and conda and still do not get it to work. 

These are the packages in the conda env
```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
alabaster                 0.7.12                   pypi_0    pypi
anndata                   0.8.0                    pypi_0    pypi
aom                       3.5.0                h27087fc_0    conda-forge
babel                     2.10.3                   pypi_0    pypi
blas                      1.0                         mkl    anaconda
blosc                     1.21.0               h4ff587b_1    anaconda
brotlipy                  0.7.0           py37h540881e_1004    conda-forge
bzip2                     1.0.8                h7b6447c_0    anaconda
c-ares                    1.18.1               h7f8727e_0    anaconda
ca-certificates           2022.9.24            ha878542_0    conda-forge
certifi                   2022.9.24          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1           py37h43b0acd_1    conda-forge
charset-normalizer        2.1.1              pyhd8ed1ab_0    conda-forge
cryptography              38.0.2           py37h5994e8b_1    conda-forge
cycler                    0.11.0                   pypi_0    pypi
docutils                  0.17.1                   pypi_0    pypi
expat                     2.5.0                h27087fc_0    conda-forge
ffmpeg                    5.1.2           gpl_hc51e5dc_103    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.1               hc2a2eb6_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.38.0                   pypi_0    pypi
freetype                  2.12.1               hca18f0e_0    conda-forge
gettext                   0.21.1               h27087fc_0    conda-forge
gmp                       6.2.1                h58526e2_0    conda-forge
gnutls                    3.7.8                hf3e180e_0    conda-forge
h5py                      3.7.0                    pypi_0    pypi
hdf5                      1.12.1          nompi_h4df4325_104    conda-forge
icu                       70.1                 h27087fc_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
imagesize                 1.4.1                    pypi_0    pypi
importlib-metadata        5.0.0                    pypi_0    pypi
intel-openmp              2021.4.0          h06a4308_3561    anaconda
jinja2                    3.1.2                    pypi_0    pypi
joblib                    1.2.0                    pypi_0    pypi
jpeg                      9e                   h166bdaf_2    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.4                    pypi_0    pypi
krb5                      1.19.3               h08a2579_0    conda-forge
lame                      3.100             h166bdaf_1003    conda-forge
lcms2                     2.13.1               h6ed2654_0    conda-forge
ld_impl_linux-64          2.39                 hc81fddc_0    conda-forge
lerc                      4.0.0                h27087fc_0    conda-forge
libcurl                   7.86.0               h2283fc2_0    conda-forge
libdeflate                1.14                 h166bdaf_0    conda-forge
libdrm                    2.4.113              h166bdaf_0    conda-forge
libedit                   3.1.20210910         h7f8727e_0    anaconda
libev                     4.33                 h7f8727e_1    anaconda
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 12.2.0              h65d4601_19    conda-forge
libgfortran-ng            11.2.0               h00389a5_1    anaconda
libgfortran5              11.2.0               h1234567_1    anaconda
libgomp                   12.2.0              h65d4601_19    conda-forge
libiconv                  1.17                 h166bdaf_0    conda-forge
libidn2                   2.3.4                h166bdaf_0    conda-forge
libnghttp2                1.47.0               hff17c54_1    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libpciaccess              0.16                 h516909a_0    conda-forge
libpng                    1.6.38               h753d276_0    conda-forge
libsqlite                 3.39.4               h753d276_0    conda-forge
libssh2                   1.10.0               hf14f497_3    conda-forge
libstdcxx-ng              12.2.0              h46fd767_19    conda-forge
libtasn1                  4.19.0               h166bdaf_0    conda-forge
libtiff                   4.4.0                h55922b4_4    conda-forge
libunistring              0.9.10               h7f98852_0    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libva                     2.16.0               h166bdaf_0    conda-forge
libvpx                    1.11.0               h9c3ff4c_3    conda-forge
libwebp-base              1.2.4                h166bdaf_0    conda-forge
libxcb                    1.13              h7f98852_1004    conda-forge
libxml2                   2.10.3               h7463322_0    conda-forge
libzlib                   1.2.13               h166bdaf_4    conda-forge
lz4-c                     1.9.3                h295c915_1    anaconda
lzo                       2.10                 h7b6447c_2    anaconda
markupsafe                2.1.1                    pypi_0    pypi
matplotlib                3.5.3                    pypi_0    pypi
mkl                       2021.4.0           h06a4308_640    anaconda
mkl-service               2.4.0            py37h7f8727e_0    anaconda
mkl_fft                   1.3.1            py37hd3c417c_0    anaconda
mkl_random                1.2.2            py37h51133e4_0    anaconda
mock                      4.0.3              pyhd3eb1b0_0    anaconda
natsort                   8.2.0                    pypi_0    pypi
ncurses                   6.3                  h27087fc_1    conda-forge
nettle                    3.8.1                hc379101_1    conda-forge
numexpr                   2.8.3            py37h807cd23_0    anaconda
numpy                     1.21.5           py37h6c91a56_3    anaconda
numpy-base                1.21.5           py37ha15fc14_3    anaconda
openh264                  2.3.1                h27087fc_1    conda-forge
openjpeg                  2.5.0                h7d73246_1    conda-forge
openssl                   3.0.5                h166bdaf_2    conda-forge
opt-einsum                3.3.0                    pypi_0    pypi
p11-kit                   0.24.1               hc5aa10d_0    conda-forge
packaging                 21.3               pyhd3eb1b0_0    anaconda
pandas                    1.3.5                    pypi_0    pypi
pillow                    9.2.0            py37h850a105_2    conda-forge
pip                       22.3               pyhd8ed1ab_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pygments                  2.13.0                   pypi_0    pypi
pyopenssl                 22.1.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.4              pyhd3eb1b0_0    anaconda
pyro-api                  0.1.2                    pypi_0    pypi
pyro-ppl                  1.8.2                    pypi_0    pypi
pysocks                   1.7.1            py37h89c1867_5    conda-forge
pytables                  3.7.0            py37h9da3b7f_0    anaconda
python                    3.7.12          hf930737_100_cpython    conda-forge
python-dateutil           2.8.2                    pypi_0    pypi
python_abi                3.7                     2_cp37m    conda-forge
pytorch                   1.13.0              py3.7_cpu_0    pytorch
pytorch-mutex             1.0                         cpu    pytorch
pytz                      2022.5                   pypi_0    pypi
readline                  8.1.2                h0f457ee_0    conda-forge
requests                  2.28.1             pyhd8ed1ab_1    conda-forge
scikit-learn              1.0.2                    pypi_0    pypi
scipy                     1.7.3                    pypi_0    pypi
setuptools                65.5.0             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyhd3eb1b0_1    anaconda
snowballstemmer           2.2.0                    pypi_0    pypi
sphinx                    5.3.0                    pypi_0    pypi
sphinx-argparse           0.3.2                    pypi_0    pypi
sphinx-autodoc-typehints  1.19.4                   pypi_0    pypi
sphinx-rtd-theme          1.0.0                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.2                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.2                    pypi_0    pypi
sphinxcontrib-htmlhelp    2.0.0                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-programoutput 0.17                     pypi_0    pypi
sphinxcontrib-qthelp      1.0.3                    pypi_0    pypi
sphinxcontrib-serializinghtml 1.1.5                    pypi_0    pypi
sqlite                    3.39.4               h4ff8645_0    conda-forge
svt-av1                   1.3.0                h27087fc_0    conda-forge
threadpoolctl             3.1.0                    pypi_0    pypi
tk                        8.6.12               h27826a3_0    conda-forge
torchvision               0.14.0                 py37_cpu    pytorch
tqdm                      4.64.1                   pypi_0    pypi
typing_extensions         4.4.0              pyha770c72_0    conda-forge
urllib3                   1.26.11            pyhd8ed1ab_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
x264                      1!164.3095           h166bdaf_2    conda-forge
x265                      3.5                  h924138e_3    conda-forge
xorg-fixesproto           5.0               h7f98852_1002    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libx11               1.7.2                h7f98852_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h7f98852_1    conda-forge
xorg-libxfixes            5.0.3             h7f98852_1004    conda-forge
xorg-xextproto            7.3.0             h7f98852_1002    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
zipp                      3.10.0             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               h166bdaf_4    conda-forge
zstd                      1.5.2                ha4553b6_0    anaconda
```

What do you think the problem is?

Thanks in advance!

**Comment by sjfleming** [comment]
Hi @ccruizm , unfortunately I am not sure what's going on... I have not seen this before.  I found [this link](https://github.com/facebookresearch/metaseq/issues/40) and I wonder if it's worth trying 

```
python3 setup.py install
```
instead of 
```
pip install -e .
```

**Comment by sjfleming** [comment]
(Also you can always try the docker image if installation is taking too much time `us.gcr.io/broad-dsde-methods/cellbender:0.2.0`)

**Comment by ccruizm** [comment]
Thank you @sjfleming for your speedy reply! I just tried it (` git clone https://github.com/broadinstitute/CellBender.git && cd CellBender && python3 setup.py install`) and it worked! but now it does not find CUDA :( I might need to use the docker image.

Any idea how can access/pull the docker file using singularity? our HPC system does not work with docker.

Thanks again!

**Comment by sjfleming** [comment]
The CUDA issue would arise if you don't install pytorch separately first.  Did you do it that way?  So I'd recommend that before you run those commands you just listed, you should follow the steps here (https://pytorch.org) to install the right version of pytorch for your hardware.

I will ask a co-worker who has used the image via singularity, and I'll get back to you.

**Comment by sjfleming** [comment]
As for the docker image on HPC that runs singularity...

Seems like you might be able to do this

```
singularity build /path/to/downloaded/image/img.simg docker://us.gcr.io/broad-dsde-methods/cellbender:0.2.0
```
and then you can do
```
singularity exec /path/to/downloaded/image/img.simg ...
```

(thanks to @mark-chaffin)

**Comment by ccruizm** [comment]
Thanks for all the help @sjfleming ! I could make it work :)
