### ISSUE TITLE
Windows Problems installing

### ISSUE THREAD

**Issue by kaylinker** [broadinstitute/CellBender#175]
Hi
I am having an issue installing CellBender on windows
Both this : 
```
conda create -n cellbender python=3.7
conda activate cellbender
conda install -c anaconda pytable
conda install pytorch torchvision -c pytorch
pip install -e CellBender
```
And this:
```
conda create -n CellBender python=3.7
conda activate CellBender
conda install -c anaconda pytables
conda install pytorch torchvision -c pytorch
git clone https://github.com/broadinstitute/CellBender.git
pip install -e CellBender
```

Got the below error message whenever I try to run `remove-background` or check the version of CellBender

```
> Traceback (most recent call last):
>   File "C:\Users\khakhlab\.conda\envs\cellbender\Scripts\cellbender-script.py", line 33, in <module>
>     sys.exit(load_entry_point('cellbender', 'console_scripts', 'cellbender')())
>   File "c:\users\khakhlab\cellbender\cellbender\base_cli.py", line 91, in main
>     cli_dict = generate_cli_dictionary()
>   File "c:\users\khakhlab\cellbender\cellbender\base_cli.py", line 52, in generate_cli_dictionary
>     module_cli = importlib.import_module('.'.join(module_cli_str_list))
>   File "C:\Users\khakhlab\.conda\envs\cellbender\lib\importlib\__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "c:\users\khakhlab\cellbender\cellbender\remove_background\cli.py", line 4, in <module>
>     from cellbender.remove_background.data.dataset import SingleCellRNACountsDataset
>   File "c:\users\khakhlab\cellbender\cellbender\remove_background\data\dataset.py", line 10, in <module>
>     import anndata
>   File "C:\Users\khakhlab\.conda\envs\cellbender\lib\site-packages\anndata\__init__.py", line 7, in <module>
>     from ._core.anndata import AnnData
>   File "C:\Users\khakhlab\.conda\envs\cellbender\lib\site-packages\anndata\_core\anndata.py", line 17, in <module>
>     import h5py
>   File "C:\Users\khakhlab\.conda\envs\cellbender\lib\site-packages\h5py\__init__.py", line 33, in <module>
>     from . import version
>   File "C:\Users\khakhlab\.conda\envs\cellbender\lib\site-packages\h5py\version.py", line 15, in <module>
>     from . import h5 as _h5
>   File "h5py\h5.pyx", line 1, in init h5py.h5
> ImportError: DLL load failed: The specified procedure could not be found.
```

Thank you so much for any help

**Comment by kaylinker** [comment]
update : It works if I don't install pytorch before cellbender

**Comment by sjfleming** [comment]
Hi @kaylinker sorry for the delay.  I have no personal experience installing on windows, so I'm afraid I might not be super helpful.

I don't know why it would give you this problem when you install pytorch before cellbender.

But it's working now?

**Comment by iheartfoosball** [comment]
FWIW, I had a similar issue on Windows. Checking CellBender version worked fine for me, but couldn't run `remove-background` if I installed CellBender after pytables and pytorch. It worked after switching to python 3.9 (from 3.7) and installing CellBender before pytorch. (I suspect omiting the pytorch installation would've worked too, but I wanted to run on GPU, so I installed the cuda-compatible version after getting an error.)

```
conda create -n CellBender3.9 python=3.9
conda activate CellBender3.9
git clone https://github.com/broadinstitute/CellBender.git
pip install e- CellBender
conda install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia
```

**Comment by Nahviss** [comment]
Colleague found a fix for this issue, for my rig (windows 11, anaconda3, python 3.10):
(CellBender) ....> pip uninstall h5py
(CellBender) ....> conda install -c anaconda h5py
..and then ">cellbender -h" revealed that module PIL was now/also missing...
(CellBender) ....> conda install -c anaconda pillow

...now if i just had an nvidia gpu rather than amd!

**Comment by yimwy** [comment]
Hi, I was able to run remove-background with solution mentioned by ktessema on my windows machine, but here comes the problem and had no luck solving the issue, as seen in screenshot below, error "value error("'shape' elements cannot be negative") valueerror: 'shape' elements cannot be negative". 


> FWIW, I had a similar issue on Windows. Checking CellBender version worked fine for me, but couldn't run `remove-background` if I installed CellBender after pytables and pytorch. It worked after switching to python 3.9 (from 3.7) and installing CellBender before pytorch. (I suspect omiting the pytorch installation would've worked too, but I wanted to run on GPU, so I installed the cuda-compatible version after getting an error.)
> 
> ```
> conda create -n CellBender3.9 python=3.9
> conda activate CellBender3.9
> git clone https://github.com/broadinstitute/CellBender.git
> pip install e- CellBender
> conda install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia
> ```

![屏幕截图 2023-08-21 111817](https://github.com/broadinstitute/CellBender/assets/62978638/24af6c46-319b-48e2-9c39-e90a91ad53b9)
