### ISSUE TITLE
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'ckpt.tar.gz.tmp' -> 'ckpt.tar.gz'

### ISSUE THREAD

**Issue by jamesjcai** [broadinstitute/CellBender#250]
In Windows machine, this is the error/warning message:

```
cellbender:remove-background: Saving a checkpoint...
cellbender:remove-background: Could not save checkpoint
cellbender:remove-background: Traceback (most recent call last):
  File "d:\miniconda3\lib\site-packages\cellbender\remove_background\checkpoint.py", line 140, in save_checkpoint
    make_tarball(files=file_list, tarball_name=tarball_name)
  File "d:\miniconda3\lib\site-packages\cellbender\remove_background\checkpoint.py", line 300, in make_tarball
    os.rename(tarball_name + '.tmp', tarball_name)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'ckpt.tar.gz.tmp' -> 'ckpt.tar.gz'

cellbender:remove-background: [epoch 005]  average training loss: 2261.7334
cellbender:remove-background: [epoch 005] average test loss: 2249.1795
cellbender:remove-background: [epoch 006]  average training loss: 2247.9869
cellbender:remove-background: Saving a checkpoint...
cellbender:remove-background: Could not save checkpoint
cellbender:remove-background: Traceback (most recent call last):
  File "d:\miniconda3\lib\site-packages\cellbender\remove_background\checkpoint.py", line 140, in save_checkpoint
    make_tarball(files=file_list, tarball_name=tarball_name)
  File "d:\miniconda3\lib\site-packages\cellbender\remove_background\checkpoint.py", line 300, in make_tarball
    os.rename(tarball_name + '.tmp', tarball_name)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'ckpt.tar.gz.tmp' -> 'ckpt.tar.gz'

```

**Comment by sjfleming** [comment]
Uh oh... in Windows, can you not do this?

```console
$ touch ckpt.tar.gz
$ touch ckpt.tar.gz.tmp
$ mv ckpt.tar.gz.tmp ckpt.tar.gz
```

or from python
```python
import os
from pathlib import Path

Path('ckpt.tar.gz').touch()
Path('ckpt.tar.gz.tmp').touch()
os.rename('ckpt.tar.gz.tmp', 'ckpt.tar.gz')
```

Do those give this same error?

**Comment by jamesjcai** [comment]
Command line is fine.

In Python, no. Here is the output:

```
(base) C:\Users\jcai>python
Python 3.10.12 | packaged by Anaconda, Inc. | (main, Jul  5 2023, 19:01:18) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
>>>
>>>
>>> import os
>>> from pathlib import Path
>>>
>>>
>>> Path('ckpt.tar.gz').touch()
>>> Path('ckpt.tar.gz.tmp').touch()
>>> os.rename('ckpt.tar.gz.tmp', 'ckpt.tar.gz')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'ckpt.tar.gz.tmp' -> 'ckpt.tar.gz'
>>>
```

**Comment by sjfleming** [comment]
Very interesting.  Thanks for reporting this!  Seems like I will need to handle this a different way for windows users.

**Comment by sjfleming** [comment]
Seems like `os.replace()` is the way to go here, rather than `os.rename()`

See https://stackoverflow.com/questions/8107352/force-overwrite-in-os-rename

**Comment by sjfleming** [comment]
@jamesjcai if you get a chance, can you try 

```python
import os
from pathlib import Path

Path('ckpt.tar.gz').touch()
Path('ckpt.tar.gz.tmp').touch()
os.replace('ckpt.tar.gz.tmp', 'ckpt.tar.gz')
```
on Windows?

**Comment by jamesjcai** [comment]
Yes, os.replace() works in Windows.

**Comment by sjfleming** [comment]
Okay great, thanks!  And thanks for reporting this.  For now, if you're able to make that change yourself and get the code to run, fantastic.  If you want to install from a branch in this repo, the `sf_windows_checkpoint_file_rename_fix` branch has the change.  It will eventually get merged into `dev` and then later it will become part of a release.

The PR is #253
