### ISSUE TITLE
Posterior computation ValueError: 'shape' elements cannot be negative

### ISSUE THREAD

**Issue by sjfleming** [broadinstitute/CellBender#252]
@yimwy posted:

Hi, I was able to run remove-background with solution mentioned by @ktessema on my windows machine, but here comes the problem and had no luck solving the issue, as seen in screenshot below, error "value error("'shape' elements cannot be negative") valueerror: 'shape' elements cannot be negative". 

_Originally posted by @yimwy in https://github.com/broadinstitute/CellBender/issues/175#issuecomment-1685568065_

**Comment by sjfleming** [comment]
Hi @yimwy, I think this issue is different enough that I am posting it here as a new issue.

Can you tell me a little bit about your dataset?  Approximately how many cells are there?  How many genes / features?

(The only reason I can think that the shape parameter might become negative is if there is an integer overflow problem...)

**Comment by huntlylee** [comment]
I'm reporting the same issue here:

cellbender remove-background --input 9303_TJ2_scVelo_anndata_raw.h5ad --output cellbender_out.h5 --cuda --epochs 50
cellbender:remove-background: CellBender 0.3.0
cellbender:remove-background: (Workflow hash 4aa32a430f)
cellbender:remove-background: 2023-08-23 16:47:40
cellbender:remove-background: Running remove-background
cellbender:remove-background: Loading data from 9303_TJ2_scVelo_anndata_raw.h5ad
cellbender:remove-background: AnnData format
cellbender:remove-background: Using `.X` for count data.
cellbender:remove-background: Features in dataset: 56984 Gene Expression
cellbender:remove-background: Trimming features for inference.
cellbender:remove-background: 30154 features have nonzero counts.
cellbender:remove-background: Prior on counts for cells is 4648
cellbender:remove-background: Prior on counts for empty droplets is 98
cellbender:remove-background: Excluding 10029 features that are estimated to have <= 0.1 background counts in cells.
cellbender:remove-background: Including 20125 features in the analysis.
cellbender:remove-background: Trimming barcodes for inference.
cellbender:remove-background: Excluding barcodes with counts below 49
cellbender:remove-background: Using 689 probable cell barcodes, plus an additional 7967 barcodes, and 54110 empty droplets.
cellbender:remove-background: Largest surely-empty droplet has 126 UMI counts.
cellbender:remove-background: Attempting to unpack tarball "ckpt.tar.gz" to C:\Users\liy45\AppData\Local\Temp\tmp30zm9i3_
cellbender:remove-background: No saved checkpoint.
cellbender:remove-background: No checkpoint loaded.
cellbender:remove-background: Running inference...
cellbender:remove-background: [epoch 001]  average training loss: 2939.3013

....

cellbender:remove-background: [epoch 050] average test loss: 1612.4731
cellbender:remove-background: Saving a checkpoint...
cellbender:remove-background: Saved checkpoint as D:\RNA seq data\taha\ckpt.tar.gz
cellbender:remove-background: 2023-08-23 16:51:47
cellbender:remove-background: Inference procedure complete.
cellbender:remove-background: Attempting to unpack tarball "ckpt.tar.gz" to C:\Users\liy45\AppData\Local\Temp\tmpun_irkni
cellbender:remove-background: Successfully unpacked tarball to C:\Users\liy45\AppData\Local\Temp\tmpun_irkni
C:\Users\liy45\AppData\Local\Temp\tmpun_irkni\4aa32a430f_args.npy
C:\Users\liy45\AppData\Local\Temp\tmpun_irkni\4aa32a430f_model.torch
C:\Users\liy45\AppData\Local\Temp\tmpun_irkni\4aa32a430f_optim.pyro
C:\Users\liy45\AppData\Local\Temp\tmpun_irkni\4aa32a430f_optim.torch
C:\Users\liy45\AppData\Local\Temp\tmpun_irkni\4aa32a430f_params.pyro
C:\Users\liy45\AppData\Local\Temp\tmpun_irkni\4aa32a430f_random.cuda
C:\Users\liy45\AppData\Local\Temp\tmpun_irkni\4aa32a430f_random.pyro
C:\Users\liy45\AppData\Local\Temp\tmpun_irkni\4aa32a430f_test.loaderstate
C:\Users\liy45\AppData\Local\Temp\tmpun_irkni\4aa32a430f_train.loaderstate
cellbender:remove-background: Posterior not currently included in checkpoint.
cellbender:remove-background: Computing posterior noise count probabilities in mini-batches.
cellbender:remove-background: Working on chunk (1/12)
cellbender:remove-background:     [0.05 mins per chunk]
cellbender:remove-background: Working on chunk (2/12)
cellbender:remove-background: Working on chunk (3/12)
cellbender:remove-background: Working on chunk (4/12)
cellbender:remove-background: Working on chunk (5/12)
cellbender:remove-background: Working on chunk (6/12)
cellbender:remove-background: Working on chunk (7/12)
cellbender:remove-background: Working on chunk (8/12)
cellbender:remove-background: Working on chunk (9/12)
cellbender:remove-background: Working on chunk (10/12)
cellbender:remove-background: Working on chunk (11/12)
cellbender:remove-background: Working on chunk (12/12)
Traceback (most recent call last):
  File "C:\Users\liy45\Anaconda3\envs\cellblender\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\liy45\Anaconda3\envs\cellblender\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\liy45\Anaconda3\envs\cellblender\Scripts\cellbender.exe\__main__.py", line 7, in <module>
  File "C:\Users\liy45\Anaconda3\envs\cellblender\lib\site-packages\cellbender\base_cli.py", line 118, in main
    cli_dict[args.tool].run(args)
  File "C:\Users\liy45\Anaconda3\envs\cellblender\lib\site-packages\cellbender\remove_background\cli.py", line 185, in run
    return main(args)
  File "C:\Users\liy45\Anaconda3\envs\cellblender\lib\site-packages\cellbender\remove_background\cli.py", line 230, in main
    posterior = run_remove_background(args)
  File "C:\Users\liy45\Anaconda3\envs\cellblender\lib\site-packages\cellbender\remove_background\run.py", line 107, in run_remove_background
    args=args,
  File "C:\Users\liy45\Anaconda3\envs\cellblender\lib\site-packages\cellbender\remove_background\posterior.py", line 125, in load_or_compute_posterior_and_save
    posterior.cell_noise_count_posterior_coo()
  File "C:\Users\liy45\Anaconda3\envs\cellblender\lib\site-packages\cellbender\remove_background\posterior.py", line 386, in cell_noise_count_posterior_coo
    self._get_cell_noise_count_posterior_coo(**kwargs)
  File "C:\Users\liy45\Anaconda3\envs\cellblender\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\liy45\Anaconda3\envs\cellblender\lib\site-packages\cellbender\remove_background\posterior.py", line 555, in _get_cell_noise_count_posterior_coo
    shape=[np.prod(self.count_matrix_shape), n_counts_max],
  File "C:\Users\liy45\Anaconda3\envs\cellblender\lib\site-packages\scipy\sparse\coo.py", line 155, in __init__
    self._shape = check_shape((M, N))
  File "C:\Users\liy45\Anaconda3\envs\cellblender\lib\site-packages\scipy\sparse\sputils.py", line 296, in check_shape
    raise ValueError("'shape' elements cannot be negative")
ValueError: 'shape' elements cannot be negative

![image](https://github.com/broadinstitute/CellBender/assets/45722526/69ff8a74-3985-4d05-98ff-88d8c57d93cd)

**Comment by sjfleming** [comment]
@huntlylee thanks for reporting.  If you get a chance, can you run the following in python (in your cellbender conda environment) and let me know what you see?

```python
from cellbender.remove_background.data.io import load_data
import numpy as np

data = load_data('9303_TJ2_scVelo_anndata_raw.h5ad')
print('input data shape:')
print(data['matrix'].shape)
print('first element of shape of the posterior COO:')
print(np.prod(data['matrix'].shape))
```

**Comment by sjfleming** [comment]
(Note to self: I think `np.prod(data['matrix'].shape, dtype=np.uint64)` might solve this, depending on the answer above.)

**Comment by ps2504** [comment]
I'm having the same issue as well at that same step.  When I run 

from cellbender.remove_background.data.io import load_data
import numpy as np

data = load_data('9303_TJ2_scVelo_anndata_raw.h5ad')
print('input data shape:')
print(data['matrix'].shape)
print('first element of shape of the posterior COO:')
print(np.prod(data['matrix'].shape))

I get:
input data shape: (2473930, 21851)
first element of shape of the posterior COO: -1776730418

when I type in:  np.prod(data['matrix'].shape, dtype=np.uint64), I get this back: 54057844430

Thanks,

**Comment by ps2504** [comment]
just to follow up. when I added the dtype=np.uint64, it did fix that issue and the process was able to continue...however, then I subsequently encounter this error, I'm not sure if it is related:

cellbender:remove-background: Computing target noise counts per gene for MCKP estimator
Traceback (most recent call last):
  File "C:\Users\SuP1\.conda\envs\cellbender\Scripts\cellbender-script.py", line 33, in <module>
    sys.exit(load_entry_point('cellbender', 'console_scripts', 'cellbender')())
  File "c:\users\sup1\downloads\cellbender-0.3.0\cellbender-0.3.0\cellbender\base_cli.py", line 123, in main
    cli_dict[args.tool].run(args)
  File "c:\users\sup1\downloads\cellbender-0.3.0\cellbender-0.3.0\cellbender\remove_background\cli.py", line 185, in run
    return main(args)
  File "c:\users\sup1\downloads\cellbender-0.3.0\cellbender-0.3.0\cellbender\remove_background\cli.py", line 230, in main
    posterior = run_remove_background(args)
  File "c:\users\sup1\downloads\cellbender-0.3.0\cellbender-0.3.0\cellbender\remove_background\run.py", line 133, in run_remove_background
    file_name=file_name,
  File "c:\users\sup1\downloads\cellbender-0.3.0\cellbender-0.3.0\cellbender\remove_background\run.py", line 237, in compute_output_denoised_counts_reports_metrics
    per_gene=True,
  File "c:\users\sup1\downloads\cellbender-0.3.0\cellbender-0.3.0\cellbender\remove_background\posterior.py", line 1578, in compute_mean_target_removal_as_function
    device=device,
  File "c:\users\sup1\downloads\cellbender-0.3.0\cellbender-0.3.0\cellbender\remove_background\estimation.py", line 150, in estimate_noise
    dtype=np.float32)
  File "c:\users\sup1\downloads\cellbender-0.3.0\cellbender-0.3.0\cellbender\remove_background\estimation.py", line 77, in _estimation_array_to_csr
    dtype=dtype,
  File "c:\users\sup1\downloads\cellbender-0.3.0\cellbender-0.3.0\cellbender\remove_background\estimation.py", line 238, in _estimation_array_to_csr
    row, col = index_converter.get_ng_indices(m_inds=m)
  File "c:\users\sup1\downloads\cellbender-0.3.0\cellbender-0.3.0\cellbender\remove_background\posterior.py", line 1536, in get_ng_indices
    raise ValueError(f'Requested m_inds out of range: '
ValueError: Requested m_inds out of range: [-2147483648 -2147483648 -2147483648 ... -2147483648 -2147483648
 -2147483648]

**Comment by huntlylee** [comment]
> @huntlylee thanks for reporting. If you get a chance, can you run the following in python (in your cellbender conda environment) and let me know what you see?
> 
> ```python
> from cellbender.remove_background.data.io import load_data
> import numpy as np
> 
> data = load_data('9303_TJ2_scVelo_anndata_raw.h5ad')
> print('input data shape:')
> print(data['matrix'].shape)
> print('first element of shape of the posterior COO:')
> print(np.prod(data['matrix'].shape))
> ```

@sjfleming 

input data shape: (273028, 56984)
first element of shape of the posterior COO: -1621641632

**Comment by sjfleming** [comment]
Thank you so much for replying @huntlylee and @ps2504 !  Okay, well, that is different than what I see on Mac and Linux.  I think it's something platform-specific about the implementation of `np.prod()`.  (It looks like you are all on Windows?)

Either way, its seems like using `uint64` can solve the problem (thanks @ps2504 !).

But that next problem you posted, @ps2504 , is almost certainly the same thing happening again.  I will try to track it down and find its fix as well.

**Comment by ps2504** [comment]
Thank you.  I am on Windows 11Pro.  I appreciate your help and efforts!

**Comment by sjfleming** [comment]
Alright, I will eventually try to get set up with a way to test on Windows, but since I'm not yet set up for that... I wonder:

Could either of you ( @ps2504 @huntlylee ) do a test run using the branch `sf_posterior_int_overflow` from this repository?

I believe integer overflow was the problem, and I attempted to fix it in two places in the code.  Hopefully those were the only problem spots.

**Comment by huntlylee** [comment]
@sjfleming sorry for the late response. I haven't had a chance to test it (I'm not familiar with how to do a branch test either). I can try to work on it if you think it necessary. Thanks for your time!

**Comment by sjfleming** [comment]
Hi @huntlylee , I think that the change introduced in #259 will solve this. @ps2504 saw the same issue and did test those new changes and found that they fixed the problem.

I will merge these changes into an "official version" as soon as we get them reviewed, but it could take some time.

In the meantime, if you need to get cellbender to run on your samples, you can try to run the code on the branch from #259 by doing the following:
```
pip install --no-cache-dir -U git+https://github.com/broadinstitute/CellBender.git@sf_posterior_int_overflow
```

**Comment by MartinKahn** [comment]
had the same issue and this fixed it for me fyi :) Thanks!

**Comment by sjfleming** [comment]
Thanks for the feedback @MartinKahn !
