### ISSUE TITLE
Unable to create HTML report (Cellbender version 0.3.0)

### ISSUE THREAD

**Issue by TeodoraTockovska** [broadinstitute/CellBender#278]
Hello Cellbender team!

I was browsing the troubleshooting page [here](https://cellbender.readthedocs.io/en/latest/troubleshooting/index.html#remove-background-troubleshooting), and it states to report any issues if HTML files fail to generate. My log file reported an error and it couldn't generate the HTML report. Please see the error message below:

```
cellbender:remove-background: Unable to create report.
cellbender:remove-background: Traceback (most recent call last):
  File "/cellbender/0.3.0/lib/python3.7/site-packages/cellbender/remove_background/run.py", line 351, in compute_output_denoised_counts_reports_metrics
    output=html_report_file,
  File "/cellbender/0.3.0/lib/python3.7/site-packages/cellbender/remove_background/report.py", line 82, in run_notebook_make_html
    title=('CellBender: ' + os.path.basename(output).replace('_report.html', '')),
  File "/cellbender/0.3.0/lib/python3.7/site-packages/cellbender/remove_background/report.py", line 59, in _postprocess_html
    with open(file, mode='r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'sample1_cellbender/cellbender_feature_bc_matrix_report.html'
```

I ran the tool using the following command, omitting "--cuda" (ran using CPU instead of GPU):

```
input_file_h5_path="../../samples/sample1/outs/raw_feature_bc_matrix.h5"
cellbender remove-background --input $input_file_h5_path --output sample1_cellbender/cellbender_feature_bc_matrix.h5
```

**Comment by sjfleming** [comment]
Thanks for reporting this!  Do you think you're seeing the same thing reported here? #273  or here? #265 

Are you using Windows?

**Comment by TeodoraTockovska** [comment]
I ran Cellbender in a linux environment (on a high performance computing cluster). I do not see any other errors and every other file generated including the CSV files. I am not seeing the same issues as #273 and #265.

**Comment by sjfleming** [comment]
Okay thanks for clarifying.  Is there any more to that traceback or error message?  It looks like it is erroring out when I try to postprocess the HTML here
https://github.com/broadinstitute/CellBender/blob/4990df713f296256577c92cab3314daeeca0f3d7/cellbender/remove_background/report.py#L80

At that point, the HTML file should already exist, but it seems the error is saying the file does not exist.  I am a bit confused because I would be expecting some other error message earlier on that indicates that the HTML was not produced for some other reason.

**Comment by TeodoraTockovska** [comment]
There are no other traceback or error messages. I can send you the entire log file. Is there an email that I can send it to?

**Comment by sjfleming** [comment]
I wonder if this is related to #273 , but it seems like the error message is different

**Comment by sjfleming** [comment]
I think I may need to be able to side-step the postprocessing function by creating a `try ... except` around it.  That would "solve" this issue and #273 .  Though I'd still love to figure out what's causing the real problem.

**Comment by jpcartailler** [comment]
FWIW, we're also experiencing the exact same issue as @TeodoraTockovska, on a Linux cluster, running CellBender v0.3.0 (from singularity container). I agree with @sjfleming as well, the error indicates the file should already exist but doesn't, so it's probably a red herring.

**Comment by MarP2606** [comment]
Hello,
I'm encountering the same error on a HPC linux environment. I run the cellranger v0.3.0 and installed it via pip in an conda environment.
Except the ones below, there are no other errors/warnings and all other output files were created successfully.

`cellbender:remove-background: Unable to create report.
cellbender:remove-background: Traceback (most recent call last):
  File "/home/.conda/envs/cellbender/lib/python3.7/site-packages/cellbender/remove_background/run.py", line 351, in compute_output_denoised_counts_reports_metrics
    output=html_report_file,
  File "/home/.conda/envs/cellbender/lib/python3.7/site-packages/cellbender/remove_background/report.py", line 82, in run_notebook_make_html
    title=('CellBender: ' + os.path.basename(output).replace('_report.html', '')),
  File "/home/.conda/envs/cellbender/lib/python3.7/site-packages/cellbender/remove_background/report.py", line 59, in _postprocess_html
    with open(file, mode='r') as f:
FileNotFoundError: [Errno 2] No such file or directory: './RSC-23/RSC-23_rref_cellbender_report.html'
`
