### ISSUE TITLE
RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasSgemm

### ISSUE THREAD

**Issue by alexcwsmith** [broadinstitute/CellBender#298]
Hello,
I just updated from 0.2 to 0.3 via Pip, Python=3.7. I also updated Torch to 1.13, CUDA 11.6, and torch.cuda.is_available() returns True. I have an Nvidia Quadro RTX8000 with 48GB VRAM.

My CUDA version is specified as compatible here: https://github.com/pytorch/pytorch/blob/main/RELEASE.md#release-compatibility-matrix

These are the specific builds I have installed in a conda environment:

```
# Name                    Version                   Build  Channel
torch                     1.13.1                   pypi_0    pypi
cudatoolkit               11.6.2              hfc3e2af_12    conda-forge
cudatoolkit-dev           11.6.0               h72bdee0_5    conda-forge
cudnn                     8.3.2.44             hed8a83a_1    conda-forge
```

and I have tried cuda drivers installed via Pip and from conda-forge with the same error.

As soon as inference starts I get:

```
RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
```
<details>
<summary> Here is the full traceback:</summary>

```
Traceback (most recent call last):
  File "/home/smith/anaconda3/envs/cellbender3/lib/python3.7/site-packages/pyro/poutine/trace_messenger.py", line 174, in __call__
    ret = self.fn(*args, **kwargs)
  File "/home/smith/anaconda3/envs/cellbender3/lib/python3.7/site-packages/pyro/poutine/messenger.py", line 12, in _context_wrap
    return fn(*args, **kwargs)
  File "/home/smith/anaconda3/envs/cellbender3/lib/python3.7/site-packages/pyro/poutine/messenger.py", line 12, in _context_wrap
    return fn(*args, **kwargs)
  File "/home/smith/anaconda3/envs/cellbender3/lib/python3.7/site-packages/pyro/poutine/messenger.py", line 12, in _context_wrap
    return fn(*args, **kwargs)
  [Previous line repeated 1 more time]
  File "/home/smith/anaconda3/envs/cellbender3/lib/python3.7/site-packages/cellbender/remove_background/model.py", line 526, in guide
    cell_prior_log=self.d_cell_loc_prior)
  File "/home/smith/anaconda3/envs/cellbender3/lib/python3.7/site-packages/cellbender/remove_background/vae/encoder.py", line 31, in __call__
    return self.forward(**kwargs)
  File "/home/smith/anaconda3/envs/cellbender3/lib/python3.7/site-packages/cellbender/remove_background/vae/encoder.py", line 47, in forward
    out[key] = value.forward(**kwargs, z=out['z']['loc'].detach())
  File "/home/smith/anaconda3/envs/cellbender3/lib/python3.7/site-packages/cellbender/remove_background/vae/encoder.py", line 307, in forward
    p_out = self.layer3(add_extra_features(x_, p_extra_features)).squeeze()
  File "/home/smith/anaconda3/envs/cellbender3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/smith/anaconda3/envs/cellbender3/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/smith/anaconda3/envs/cellbender3/lib/python3.7/site-packages/pyro/poutine/trace_messenger.py", line 174, in __call__
    ret = self.fn(*args, **kwargs)
  File "/home/smith/anaconda3/envs/cellbender3/lib/python3.7/site-packages/pyro/poutine/handlers.py", line 205, in _fn
    return ftr(*args, **kwargs)
  File "/home/smith/anaconda3/envs/cellbender3/lib/python3.7/site-packages/pyro/poutine/trace_messenger.py", line 180, in __call__
    raise exc from e
  File "/home/smith/anaconda3/envs/cellbender3/lib/python3.7/site-packages/pyro/poutine/trace_messenger.py", line 174, in __call__
    ret = self.fn(*args, **kwargs)
  File "/home/smith/anaconda3/envs/cellbender3/lib/python3.7/site-packages/pyro/poutine/messenger.py", line 12, in _context_wrap
    return fn(*args, **kwargs)
  File "/home/smith/anaconda3/envs/cellbender3/lib/python3.7/site-packages/pyro/poutine/messenger.py", line 12, in _context_wrap
    return fn(*args, **kwargs)
  File "/home/smith/anaconda3/envs/cellbender3/lib/python3.7/site-packages/pyro/poutine/messenger.py", line 12, in _context_wrap
    return fn(*args, **kwargs)
  [Previous line repeated 1 more time]
  File "/home/smith/anaconda3/envs/cellbender3/lib/python3.7/site-packages/cellbender/remove_background/model.py", line 526, in guide
    cell_prior_log=self.d_cell_loc_prior)
  File "/home/smith/anaconda3/envs/cellbender3/lib/python3.7/site-packages/cellbender/remove_background/vae/encoder.py", line 31, in __call__
    return self.forward(**kwargs)
  File "/home/smith/anaconda3/envs/cellbender3/lib/python3.7/site-packages/cellbender/remove_background/vae/encoder.py", line 47, in forward
    out[key] = value.forward(**kwargs, z=out['z']['loc'].detach())
  File "/home/smith/anaconda3/envs/cellbender3/lib/python3.7/site-packages/cellbender/remove_background/vae/encoder.py", line 307, in forward
    p_out = self.layer3(add_extra_features(x_, p_extra_features)).squeeze()
  File "/home/smith/anaconda3/envs/cellbender3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/smith/anaconda3/envs/cellbender3/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
                       Trace Shapes:          
                        Param Sites:          
encoder_z$$$network.0.layer.0.weight 512 18629
  encoder_z$$$network.0.layer.0.bias       512
          encoder_z$$$loc_out.weight  64   512
            encoder_z$$$loc_out.bias        64
          encoder_z$$$sig_out.weight  64   512
            encoder_z$$$sig_out.bias        64
       encoder_other$$$layer1.weight 512 18633
         encoder_other$$$layer1.bias       512
   encoder_other$$$batchnorm1.weight       512
     encoder_other$$$batchnorm1.bias       512
       encoder_other$$$layer2.weight 512   516
         encoder_other$$$layer2.bias       512
   encoder_other$$$batchnorm2.weight       512
     encoder_other$$$batchnorm2.bias       512
       encoder_other$$$layer3.weight   1   516
         encoder_other$$$layer3.bias         1
encoder_other$$$eps_network.0.weight 512 18633
  encoder_other$$$eps_network.0.bias       512
encoder_other$$$eps_network.1.weight       512
  encoder_other$$$eps_network.1.bias       512
encoder_other$$$eps_network.3.weight 512   512
  encoder_other$$$eps_network.3.bias       512
encoder_other$$$eps_network.4.weight       512
  encoder_other$$$eps_network.4.bias       512
encoder_other$$$eps_network.6.weight   1   512
  encoder_other$$$eps_network.6.bias         1
   encoder_other$$$batchnorm0.weight     18629
     encoder_other$$$batchnorm0.bias     18629
                        d_cell_scale         1
                         d_empty_loc          
                       d_empty_scale          
                         chi_ambient     18629
                           rho_alpha          
                            rho_beta          
                             phi_loc          
                           phi_scale          
                       Sample Sites:          
                            phi dist         |
                               value         |
                           data dist         |
                               value 255     |
                            rho dist 255     |
                               value 255     |
                        d_empty dist 255     |
                               value 255     |

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/smith/anaconda3/envs/cellbender3/bin/cellbender", line 8, in <module>
    sys.exit(main())
  File "/home/smith/anaconda3/envs/cellbender3/lib/python3.7/site-packages/cellbender/base_cli.py", line 118, in main
    cli_dict[args.tool].run(args)
  File "/home/smith/anaconda3/envs/cellbender3/lib/python3.7/site-packages/cellbender/remove_background/cli.py", line 185, in run
    return main(args)
  File "/home/smith/anaconda3/envs/cellbender3/lib/python3.7/site-packages/cellbender/remove_background/cli.py", line 230, in main
    posterior = run_remove_background(args)
  File "/home/smith/anaconda3/envs/cellbender3/lib/python3.7/site-packages/cellbender/remove_background/run.py", line 95, in run_remove_background
    inferred_model, _, _, _ = run_inference(dataset_obj=dataset_obj, args=args)
  File "/home/smith/anaconda3/envs/cellbender3/lib/python3.7/site-packages/cellbender/remove_background/run.py", line 750, in run_inference
    final_elbo_fail_fraction=args.final_elbo_fail_fraction)
  File "/home/smith/anaconda3/envs/cellbender3/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/home/smith/anaconda3/envs/cellbender3/lib/python3.7/site-packages/cellbender/remove_background/train.py", line 178, in run_training
    total_epoch_loss_train = train_epoch(svi, train_loader)
  File "/home/smith/anaconda3/envs/cellbender3/lib/python3.7/site-packages/cellbender/remove_background/train.py", line 60, in train_epoch
    epoch_loss += svi.step(x_cell_batch)
  File "/home/smith/anaconda3/envs/cellbender3/lib/python3.7/site-packages/pyro/infer/svi.py", line 145, in step
    loss = self.loss_and_grads(self.model, self.guide, *args, **kwargs)
  File "/home/smith/anaconda3/envs/cellbender3/lib/python3.7/site-packages/pyro/infer/traceenum_elbo.py", line 451, in loss_and_grads
    for model_trace, guide_trace in self._get_traces(model, guide, args, kwargs):
  File "/home/smith/anaconda3/envs/cellbender3/lib/python3.7/site-packages/pyro/infer/traceenum_elbo.py", line 394, in _get_traces
    yield self._get_trace(model, guide, args, kwargs)
  File "/home/smith/anaconda3/envs/cellbender3/lib/python3.7/site-packages/pyro/infer/traceenum_elbo.py", line 340, in _get_trace
    "flat", self.max_plate_nesting, model, guide, args, kwargs
  File "/home/smith/anaconda3/envs/cellbender3/lib/python3.7/site-packages/pyro/infer/enum.py", line 61, in get_importance_trace
    *args, **kwargs
  File "/home/smith/anaconda3/envs/cellbender3/lib/python3.7/site-packages/pyro/poutine/trace_messenger.py", line 198, in get_trace
    self(*args, **kwargs)
  File "/home/smith/anaconda3/envs/cellbender3/lib/python3.7/site-packages/pyro/poutine/trace_messenger.py", line 180, in __call__
    raise exc from e
  File "/home/smith/anaconda3/envs/cellbender3/lib/python3.7/site-packages/pyro/poutine/trace_messenger.py", line 174, in __call__
    ret = self.fn(*args, **kwargs)
  File "/home/smith/anaconda3/envs/cellbender3/lib/python3.7/site-packages/pyro/poutine/handlers.py", line 205, in _fn
    return ftr(*args, **kwargs)
  File "/home/smith/anaconda3/envs/cellbender3/lib/python3.7/site-packages/pyro/poutine/trace_messenger.py", line 180, in __call__
    raise exc from e
  File "/home/smith/anaconda3/envs/cellbender3/lib/python3.7/site-packages/pyro/poutine/trace_messenger.py", line 174, in __call__
    ret = self.fn(*args, **kwargs)
  File "/home/smith/anaconda3/envs/cellbender3/lib/python3.7/site-packages/pyro/poutine/messenger.py", line 12, in _context_wrap
    return fn(*args, **kwargs)
  File "/home/smith/anaconda3/envs/cellbender3/lib/python3.7/site-packages/pyro/poutine/messenger.py", line 12, in _context_wrap
    return fn(*args, **kwargs)
  File "/home/smith/anaconda3/envs/cellbender3/lib/python3.7/site-packages/pyro/poutine/messenger.py", line 12, in _context_wrap
    return fn(*args, **kwargs)
  [Previous line repeated 1 more time]
  File "/home/smith/anaconda3/envs/cellbender3/lib/python3.7/site-packages/cellbender/remove_background/model.py", line 526, in guide
    cell_prior_log=self.d_cell_loc_prior)
  File "/home/smith/anaconda3/envs/cellbender3/lib/python3.7/site-packages/cellbender/remove_background/vae/encoder.py", line 31, in __call__
    return self.forward(**kwargs)
  File "/home/smith/anaconda3/envs/cellbender3/lib/python3.7/site-packages/cellbender/remove_background/vae/encoder.py", line 47, in forward
    out[key] = value.forward(**kwargs, z=out['z']['loc'].detach())
  File "/home/smith/anaconda3/envs/cellbender3/lib/python3.7/site-packages/cellbender/remove_background/vae/encoder.py", line 307, in forward
    p_out = self.layer3(add_extra_features(x_, p_extra_features)).squeeze()
  File "/home/smith/anaconda3/envs/cellbender3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/smith/anaconda3/envs/cellbender3/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
                       Trace Shapes:          
                        Param Sites:          
encoder_z$$$network.0.layer.0.weight 512 18629
  encoder_z$$$network.0.layer.0.bias       512
          encoder_z$$$loc_out.weight  64   512
            encoder_z$$$loc_out.bias        64
          encoder_z$$$sig_out.weight  64   512
            encoder_z$$$sig_out.bias        64
       encoder_other$$$layer1.weight 512 18633
         encoder_other$$$layer1.bias       512
   encoder_other$$$batchnorm1.weight       512
     encoder_other$$$batchnorm1.bias       512
       encoder_other$$$layer2.weight 512   516
         encoder_other$$$layer2.bias       512
   encoder_other$$$batchnorm2.weight       512
     encoder_other$$$batchnorm2.bias       512
       encoder_other$$$layer3.weight   1   516
         encoder_other$$$layer3.bias         1
encoder_other$$$eps_network.0.weight 512 18633
  encoder_other$$$eps_network.0.bias       512
encoder_other$$$eps_network.1.weight       512
  encoder_other$$$eps_network.1.bias       512
encoder_other$$$eps_network.3.weight 512   512
  encoder_other$$$eps_network.3.bias       512
encoder_other$$$eps_network.4.weight       512
  encoder_other$$$eps_network.4.bias       512
encoder_other$$$eps_network.6.weight   1   512
  encoder_other$$$eps_network.6.bias         1
   encoder_other$$$batchnorm0.weight     18629
     encoder_other$$$batchnorm0.bias     18629
                        d_cell_scale         1
                         d_empty_loc          
                       d_empty_scale          
                         chi_ambient     18629
                           rho_alpha          
                            rho_beta          
                             phi_loc          
                           phi_scale          
                       Sample Sites:          
                            phi dist         |
                               value         |
                           data dist         |
                               value 255     |
                            rho dist 255     |
                               value 255     |
                        d_empty dist 255     |
                               value 255     |
                       Trace Shapes:          
                        Param Sites:          
encoder_z$$$network.0.layer.0.weight 512 18629
  encoder_z$$$network.0.layer.0.bias       512
          encoder_z$$$loc_out.weight  64   512
            encoder_z$$$loc_out.bias        64
          encoder_z$$$sig_out.weight  64   512
            encoder_z$$$sig_out.bias        64
       encoder_other$$$layer1.weight 512 18633
         encoder_other$$$layer1.bias       512
   encoder_other$$$batchnorm1.weight       512
     encoder_other$$$batchnorm1.bias       512
       encoder_other$$$layer2.weight 512   516
         encoder_other$$$layer2.bias       512
   encoder_other$$$batchnorm2.weight       512
     encoder_other$$$batchnorm2.bias       512
       encoder_other$$$layer3.weight   1   516
         encoder_other$$$layer3.bias         1
encoder_other$$$eps_network.0.weight 512 18633
  encoder_other$$$eps_network.0.bias       512
encoder_other$$$eps_network.1.weight       512
  encoder_other$$$eps_network.1.bias       512
encoder_other$$$eps_network.3.weight 512   512
  encoder_other$$$eps_network.3.bias       512
encoder_other$$$eps_network.4.weight       512
  encoder_other$$$eps_network.4.bias       512
encoder_other$$$eps_network.6.weight   1   512
  encoder_other$$$eps_network.6.bias         1
   encoder_other$$$batchnorm0.weight     18629
     encoder_other$$$batchnorm0.bias     18629
                        d_cell_scale         1
                         d_empty_loc          
                       d_empty_scale          
                         chi_ambient     18629
                           rho_alpha          
                            rho_beta          
                             phi_loc          
                           phi_scale          
                       Sample Sites:          
                            phi dist         |
                               value         |
                           data dist         |
                               value 255     |
                            rho dist 255     |
                               value 255     |
                        d_empty dist 255     |
                               value 255     |

```
</details>

**Comment by tsotnech** [comment]
I run into the same error at "Computing target noise counts per gene for MCKP estimator" step.

**Comment by AClab-sgarcia** [comment]
I am also getting same error

**Comment by hoductrung138-star** [comment]
I ran into the same error
