### ISSUE TITLE
Error generating HTML report?

### ISSUE THREAD

**Issue by razorofockham** [broadinstitute/CellBender#327]
First of all, thanks for this super nice tool!

I just ran CellBender for the first time, and although the run apparently finished successfully, and the HTML report was actually generated (and it looks good to me), I get the following at the very end:

```
cellbender:remove-background: Succeeded in writing CellRanger format output to file CM0_New_CellBender.h5
cellbender:remove-background: Succeeded in writing CellRanger format output to file CM0_New_CellBender_filtered.h5
cellbender:remove-background: Saved output metrics as CM0_New_CellBender_metrics.csv
[NbConvertApp] Converting notebook tmp.report.ipynb to notebook
[NbConvertApp] Writing 531555 bytes to tmp.report.nbconvert.ipynb
[NbConvertApp] Converting notebook tmp.report.nbconvert.ipynb to html
[NbConvertApp] Writing 1106224 bytes to tmp.report.nbconvert.html
cellbender:remove-background: Unable to create report.
cellbender:remove-background: Traceback (most recent call last):
File "/home/razorofockham/miniconda3/envs/CellBender/lib/python3.7/site-packages/cellbender/remove_background/run.py", line 351, in compute_output_denoised_counts_reports_metrics
output=html_report_file,
File "/home/razorofockham/miniconda3/envs/CellBender/lib/python3.7/site-packages/cellbender/remove_background/report.py", line 82, in run_notebook_make_html
title=('CellBender: ' + os.path.basename(output).replace('_report.html', '')),
File "/home/razorofockham/miniconda3/envs/CellBender/lib/python3.7/site-packages/cellbender/remove_background/report.py", line 60, in _postprocess_html
html = f.read()
File "/home/razorofockham/miniconda3/envs/CellBender/lib/python3.7/encodings/ascii.py", line 26, in decode
return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xee in position 232667: ordinal not in range(128)
cellbender:remove-background: Completed remove-background.
cellbender:remove-background: 2024-02-02 17:04:08
```

I just thought I would let you know, since I saw the note about potential issues with the reports in v0.3.0 in the Troubleshooting section of the documentation. Also, is there something I can check in the HTML report to make sure nothing is missing?

In case it helps, I am running `cellbender 0.3.0` within WSL2 (Debian 11) using `python 3.7.12`, `pytorch 1.13.1`, and `pytorch-cuda 11.7`.

Thanks!

-Juan

**Comment by jpintar** [comment]
I'm getting the same error on a CentOS 7 node, so it's not a WSL-only issue (also using `cellbender=0.3.0`, `python=3.7.12`). The HTML report was generated anyway and looks fine. The issue doesn't affect all datasets (I haven't tried re-running the affected ones to see whether it happens on every run, but I can if it would be helpful).

**Comment by OneHitKO** [comment]
I was able to solve the html error by pip installing `lxml-html-clean` in an environment containing `cellbender=0.3.0` and `python=3.7`.
