### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by IrinaVKuznetsova** [broadinstitute/CellBender#328]
Hi, 

I have 8 samples, only one got this error message:
 
```
cellbender:remove-background: Writing full posterior to ***/cellbender_feature_bc_matrix_posterior.h5
cellbender:remove-background: Succeeded in writing posterior to file ***/cellbender_feature_bc_matrix_posterior.h5
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/rna/cellbender/lib/python3.7/shutil.py", line 122, in copyfile
    copyfileobj(fsrc, fdst)
  File "/home/ubuntu/miniconda3/envs/rna/cellbender/lib/python3.7/shutil.py", line 82, in copyfileobj
    fdst.write(buf)
OSError: [Errno 28] No space left on device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/rna/cellbender/bin/cellbender", line 8, in <module>
    sys.exit(main())
  File "/data/bin/CellBender/cellbender/base_cli.py", line 118, in main
    cli_dict[args.tool].run(args)
  File "/data/bin/CellBender/cellbender/remove_background/cli.py", line 185, in run
    return main(args)
  File "/data/bin/CellBender/cellbender/remove_background/cli.py", line 219, in main
    posterior = run_remove_background(args)
  File "/data/bin/CellBender/cellbender/remove_background/run.py", line 126, in run_remove_background
    args=args,
  File "/data/bin/CellBender/cellbender/remove_background/posterior.py", line 137, in load_or_compute_posterior_and_save
    shutil.copy(posterior_file, os.path.join(tmp_dir, 'posterior.h5'))
  File "/home/ubuntu/miniconda3/envs/rna/cellbender/lib/python3.7/shutil.py", line 248, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/ubuntu/miniconda3/envs/rna/cellbender/lib/python3.7/shutil.py", line 122, in copyfile
    copyfileobj(fsrc, fdst)
OSError: [Errno 28] No space left on device
```

The command:
```
  cellbender remove-background \
    --input "$raw_feature_bc_matrix" \
    --output "$cellbender_feature_bc_matrix.h5 \
    --fpr 0.01 \
    --epochs 150 \
    --low-count-threshold 5 \
    --learning-rate 0.0001
```

Any fixer for this?
Thank you

**Comment by IrinaVKuznetsova** [comment]
I reduced a learning rate to  a half - 0.00005, and got results.
Can you please help me to assess results.
From the "Cell probabilities" plot, it looks like its a very high chance that droplets contain cells, meaning no empty droplets. 
From the "Examine how many counts were removed in total" plot we have a very high % of noise counts removed from non-empty droplets (~23%)
The "Examine count removal per gene" plot shows negative correlation, but if we almost don't have empty droplets that kind of make sense, is it a correct logic to the interpretation of these results?   
![image](https://github.com/broadinstitute/CellBender/assets/37644569/b59cef64-de92-440d-af24-40bb195916d7)

in comparison below is results example for another sample
![image](https://github.com/broadinstitute/CellBender/assets/37644569/ab78d858-3f35-42d2-9f94-e84d96eaffb6)


thank you
