### ISSUE TITLE
CellBender ran successfully but no HTML report generated

### ISSUE THREAD

**Issue by wendy0853** [broadinstitute/CellBender#337]
Hello! 

This is my first time running CellBender and I'm so happy I got it to work! However, when looking over the output files, it seems like I'm missing an output_report.html file. Below is the log for the failure. I used python3.8 and CellBender v0.3.1. Please let me know if there's anything I can do to obtain the html summary. Thanks!

```
cellbender:remove-background: Working on chunk (5/6)
cellbender:remove-background: Working on chunk (6/6)
cellbender:remove-background: 2024-02-26 20:42:04 Total MCKP estimation time = 94.20 sec
cellbender:remove-background: Succeeded in writing CellRanger format output to file cellbender_results.h5
cellbender:remove-background: Succeeded in writing CellRanger format output to file cellbender_results_filtered.h5
cellbender:remove-background: Saved output metrics as cellbender_results_metrics.csv
cellbender:remove-background: Unable to create report.
cellbender:remove-background: Traceback (most recent call last):
  File "/Users/wendy/Documents/Programming/Programming/snRNA-Seq//CellBender/cellbender/remove_background/run.py", line 368, in compute_output_denoised_counts_reports_metrics
    run_notebook_make_html(
  File "/Users/wendy/Documents/Programming/Programming/snRNA-Seq//CellBender/cellbender/remove_background/report.py", line 84, in run_notebook_make_html
    html_file = _to_html(file=_run_notebook(file), output=output)
  File "/Users/wendy/Documents/Programming/Programming/snRNA-Seq//CellBender/cellbender/remove_background/report.py", line 54, in _to_html
    os.replace(file.replace(".ipynb", ".html"), output)
FileNotFoundError: [Errno 2] No such file or directory: 'tmp.report.nbconvert.html' -> 'cellbender_results_report.html'

cellbender:remove-background: Completed remove-background.
cellbender:remove-background: 2024-02-26 20:42:16
```

**Comment by shanshenbing** [comment]
I got same errors.

**Comment by ashipde** [comment]
Same, with latest version set up in Conda on Linux

**Comment by ludivine009** [comment]
Hi,
Thanks for developing CellBender! 
I also got the same error today using python 3.7.16 and cellbender 0.3.0 in conda. 
Thank you

**Comment by ashipde** [comment]
> Same, with latest version set up in Conda on Linux

With latest/master version (19 April), the issue no longer arises in my setup.

**Comment by natalie-23-gill** [comment]
I am having a similar issue with the official 0.3.0 docker image

```
cellbender:remove-background: Unable to create report.
cellbender:remove-background: Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/cellbender/remove_background/run.py", line 351, in compute_output_denoised_counts_reports_metrics
    output=html_report_file,
  File "/opt/conda/lib/python3.7/site-packages/cellbender/remove_background/report.py", line 82, in run_notebook_make_html
    title=('CellBender: ' + os.path.basename(output).replace('_report.html', '')),
  File "/opt/conda/lib/python3.7/site-packages/cellbender/remove_background/report.py", line 59, in _postprocess_html
    with open(file, mode='r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'cellbender_report.html'

cellbender:remove-background: Completed remove-background.
cellbender:remove-background: 2024-05-03 19:42:01
```

**Comment by zofieLin** [comment]
I got the same error message using python 3.7.16 and cellbender 0.3.0 in linux-x64

**Comment by zofieLin** [comment]
> I got the same error message using python 3.7.16 and cellbender 0.3.0 in linux-x64

fixed after pip install lxml_html_clean

**Comment by jasonleongbio** [comment]
The solution provided by @zofieLin worked for me (virtual environment on both my macOS and my Linux server). 
```
pip install lxml_html_clean
```
Thanks so much!

I didn't encounter this problem when I was using v0.3.1.
But now as the software has been temporarily downgraded to v0.3.0 (due to a bug announced on the main page), this error message showed up after running the program for almost a whole day. 
Strongly suggest the developer team should add this to the installation instructions.

**Comment by hgildea** [comment]
I'm also using an old version for GPU compatibility, but I fail to generate the html file even after installing via pip install lxml_html_clean in my environment. Any other thoughts on this?

**Comment by sjfleming** [comment]
Thanks for helping out everybody!  Yes `lxml_html_clean` did become a dependency in the move from v0.3.0 to v0.3.2
https://github.com/broadinstitute/CellBender/blob/609419a397d4723819656fd288a28d19abcfb6b3/requirements.txt#L15
v0.3.2 has been officially released, but it looks like I still need to publish it on pypi.  (I would still expect the v0.3.0 docker image to work fine though, since all the software is encapsulated there.)

In general though, the HTML creation process is a bit fragile unfortunately due to all its dependencies on jupyter, which is very actively updated. (I cannot think why something would succeed once using the docker image and then fail later though, that is not at all clear to me... it should not happen.)

If you ever have a run where everything works except for HTML report generation, you always have the option of grabbing the jupyter notebook file from this repo
https://github.com/broadinstitute/CellBender/blob/master/cellbender/remove_background/report.ipynb

and running in manually by replacing `input_file` with the raw count input you used to run cellbender, and replacing `output_file` with the full cellbender h5 output.  Running the cell in the "Report" section generates the entire report.  That report is identical to the report that cellbender actually creates.

**Comment by sjfleming** [comment]
Everyone though, please be warned: v0.3.1 has been yanked due to a serious bug in output count generation.  (There was an issue with an integer overflow that caused outputs to be incorrect.)  The problem was fixed in v0.3.2, and the problem did not exist in v0.3.0.

**Comment by BenjaminDEMAILLE** [comment]
Same error for me
