### ISSUE TITLE
Unhandled division by zero

### ISSUE THREAD

**Issue by fm361** [broadinstitute/CellBender#363]
Hello,

I'm trying to run cellbender 0.3.0 (python 3.8.19) on 10X data aligned with STARsolo. The data are quite shallow, so I expect lots of droplets with very low counts.

I repeatedly run into the following issue, which seems to be an edge case that is not handled.

```
cellbender:remove-background: Command:
cellbender remove-background --input Solo.out/Gene/raw --output Solo.out/Gene/cellbender.h5 --expected-cells 5000 --model full --z-dim 64 --z-layers 512 --estimator-multiple-cpu
cellbender:remove-background: CellBender 0.3.0
cellbender:remove-background: (Workflow hash f46bbc8ba0)
cellbender:remove-background: 2024-05-30 09:44:08
cellbender:remove-background: Running remove-background
cellbender:remove-background: Loading data from Solo.out/Gene/raw
cellbender:remove-background: CellRanger v2 format
cellbender:remove-background: Features in dataset: 38606 NA
cellbender:remove-background: Trimming features for inference.
cellbender:remove-background: 14717 features have nonzero counts.
cellbender:remove-background: Prior on counts for cells is 24
cellbender:remove-background: Prior on counts for empty droplets is 1
Traceback (most recent call last):
  File "/mnt/data/micromamba/envs/my_env/bin/cellbender", line 33, in <module>
    sys.exit(load_entry_point('cellbender', 'console_scripts', 'cellbender')())
  File "/mnt/data/micromamba/envs/my_env/opt/CellBender/cellbender/base_cli.py", line 123, in main
    cli_dict[args.tool].run(args)
  File "/mnt/data/micromamba/envs/my_env/opt/CellBender/cellbender/remove_background/cli.py", line 185, in run
    return main(args)
  File "/mnt/data/micromamba/envs/my_env/opt/CellBender/cellbender/remove_background/cli.py", line 230, in main
    posterior = run_remove_background(args)
  File "/mnt/data/micromamba/envs/my_env/opt/CellBender/cellbender/remove_background/run.py", line 84, in run_remove_background
    dataset_obj = get_dataset_obj(args=args)
  File "/mnt/data/micromamba/envs/my_env/opt/CellBender/cellbender/remove_background/data/dataset.py", line 526, in get_dataset_obj
    return SingleCellRNACountsDataset(
  File "/mnt/data/micromamba/envs/my_env/opt/CellBender/cellbender/remove_background/data/dataset.py", line 167, in __init__
    self._trim_noiseless_features()
  File "/mnt/data/micromamba/envs/my_env/opt/CellBender/cellbender/remove_background/data/dataset.py", line 290, in _trim_noiseless_features
    mean_counts_per_empty_g = np.array(count_matrix_empties.mean(axis=0)).squeeze()
  File "/mnt/data/micromamba/envs/my_env/lib/python3.8/site-packages/scipy/sparse/_base.py", line 1191, in mean
    return (inter_self * (1.0 / self.shape[0])).sum(
ZeroDivisionError: float division by zero
```

**Comment by CedricHerzog** [comment]
Hi,

I have the same error here with cellbender 0.3.2 and python 3.7.12

**Comment by Claptar** [comment]
Hi! I have the same issue. 

Cellbender calculates its own priors for cell and droplet counts. In your case the prior for empty-droplets equals 1, so when cellbender tries to filter those cells you get an empty set.

```
cutoff = self.priors['empty_count_upper_limit']
count_matrix_empties = count_matrix[(counts < cutoff)
                                    & (counts > self.low_count_threshold), :]
```

In my case I manually set  argument `--low-count-threshold 50` while the prior equals 2, which also resulted in an empty set in intersection.

To solve this there is a flag `--force-empty-umi-prior` to specify the lower bound for cutoff
