### ISSUE TITLE
Save checkpoint fails

### ISSUE THREAD

**Issue by christophista** [broadinstitute/CellBender#395]
Hello

Thank you for providing cellbender. I am trying to use it on a Debian/Bookworm machine with an A10 GPU. The python (3.10) environment is attached later in this message. 

The script trains for some 150 epochs when it tries to generate the checkpoint file, which fails. The error message is attached. No parameters other than --cuda and the input h5 and output file were provided for the run. 

May I please ask for your guidance on how to resolve the issue? 

Many thanks in advance
Best regards, chrsitoph

Error message (truncated:)
```
cellbender:remove-background: Saving a checkpoint...
cellbender:remove-background: Could not save checkpoint
cellbender:remove-background: Traceback (most recent call last):
  File "./AmbientDNAremoval/cellbender_venv/lib/python3.10/site-packages/cellbender/remove_background/checkpoint.py", line 115, in save_checkpoint
    torch.save(model_obj, filebase + '_model.torch')
  File "./AmbientDNAremoval/cellbender_venv/lib/python3.10/site-packages/torch/serialization.py", line 850, in save
    _save(
  File "./AmbientDNAremoval/cellbender_venv/lib/python3.10/site-packages/torch/serialization.py", line 1088, in _save
    pickler.dump(obj)
TypeError: cannot pickle 'weakref.ReferenceType' object

cellbender:remove-background: 2024-11-18 16:15:32
cellbender:remove-background: Inference procedure complete.
Traceback (most recent call last):
  File "./AmbientDNAremoval/./cellbender_venv/bin/cellbender", line 10, in <module>
    sys.exit(main())
  File "./AmbientDNAremoval/cellbender_venv/lib/python3.10/site-packages/cellbender/base_cli.py", line 118, in main
    cli_dict[args.tool].run(args)
  File "./AmbientDNAremoval/cellbender_venv/lib/python3.10/site-packages/cellbender/remove_background/cli.py", line 185, in run
    return main(args)
  File "./AmbientDNAremoval/cellbender_venv/lib/python3.10/site-packages/cellbender/remove_background/cli.py", line 230, in main
    posterior = run_remove_background(args)
  File "./AmbientDNAremoval/cellbender_venv/lib/python3.10/site-packages/cellbender/remove_background/run.py", line 104, in run_remove_background
    posterior = load_or_compute_posterior_and_save(
  File "./AmbientDNAremoval/cellbender_venv/lib/python3.10/site-packages/cellbender/remove_background/posterior.py", line 59, in load_or_compute_posterior_and_save
    assert os.path.exists(args.input_checkpoint_tarball), \
AssertionError: Checkpoint file ckpt.tar.gz does not exist, presumably because saving of the checkpoint file has been manually interrupted. load_or_compute_posterior_and_save() will not work properly without an existing checkpoint file. Please re-run and allow a checkpoint file to be saved.
```

venv environment
```
anndata==0.11.1
anyio==4.6.2.post1
argon2-cffi==23.1.0
argon2-cffi-bindings==21.2.0
array_api_compat==1.9.1
arrow==1.3.0
asttokens==2.4.1
async-lru==2.0.4
attrs==24.2.0
babel==2.16.0
beautifulsoup4==4.12.3
bleach==6.2.0
blosc2==2.7.1
cellbender==0.3.0
certifi==2024.8.30
cffi==1.17.1
charset-normalizer==3.4.0
click==8.1.7
comm==0.2.2
contourpy==1.3.1
cycler==0.12.1
debugpy==1.8.8
decorator==5.1.1
defusedxml==0.7.1
entrypoints==0.4
exceptiongroup==1.2.2
executing==2.1.0
fastjsonschema==2.20.0
filelock==3.16.1
fonttools==4.55.0
fqdn==1.5.1
fsspec==2024.10.0
h11==0.14.0
h5py==3.12.1
httpcore==1.0.7
httpx==0.27.2
idna==3.10
ipykernel==6.29.5
ipython==8.29.0
ipython-genutils==0.2.0
ipywidgets==8.1.5
isoduration==20.11.0
jedi==0.19.2
Jinja2==3.1.4
json5==0.9.28
jsonpointer==3.0.0
jsonschema==4.23.0
jsonschema-specifications==2024.10.1
jupyter==1.1.1
jupyter-console==6.6.3
jupyter-contrib-core==0.4.2
jupyter-contrib-nbextensions==0.7.0
jupyter-events==0.10.0
jupyter-highlight-selected-word==0.2.0
jupyter-lsp==2.2.5
jupyter_client==7.4.9
jupyter_core==5.7.2
jupyter_nbextensions_configurator==0.6.4
jupyter_server==2.14.2
jupyter_server_terminals==0.5.3
jupyterlab==4.3.1
jupyterlab_pygments==0.3.0
jupyterlab_server==2.27.3
jupyterlab_widgets==3.0.13
kiwisolver==1.4.7
llvmlite==0.43.0
loompy==3.0.7
lxml==5.3.0
MarkupSafe==3.0.2
matplotlib==3.9.2
matplotlib-inline==0.1.7
mistune==0.8.4
mpmath==1.3.0
msgpack==1.1.0
natsort==8.4.0
nbclassic==1.1.0
nbclient==0.10.0
nbconvert==6.5.4
nbformat==5.10.4
ndindex==1.9.2
nest-asyncio==1.6.0
networkx==3.4.2
notebook==6.5.7
notebook_shim==0.2.4
numba==0.60.0
numexpr==2.10.1
numpy==2.0.2
numpy-groupies==0.11.2
nvidia-cublas-cu12==12.4.5.8
nvidia-cuda-cupti-cu12==12.4.127
nvidia-cuda-nvrtc-cu12==12.4.127
nvidia-cuda-runtime-cu12==12.4.127
nvidia-cudnn-cu12==9.1.0.70
nvidia-cufft-cu12==11.2.1.3
nvidia-curand-cu12==10.3.5.147
nvidia-cusolver-cu12==11.6.1.9
nvidia-cusparse-cu12==12.3.1.170
nvidia-nccl-cu12==2.21.5
nvidia-nvjitlink-cu12==12.4.127
nvidia-nvtx-cu12==12.4.127
opt_einsum==3.4.0
overrides==7.7.0
packaging==24.2
pandas==2.2.3
pandocfilters==1.5.1
parso==0.8.4
pexpect==4.9.0
pillow==11.0.0
platformdirs==4.3.6
prometheus_client==0.21.0
prompt_toolkit==3.0.48
psutil==6.1.0
ptyprocess==0.7.0
pure_eval==0.2.3
py-cpuinfo==9.0.0
pycparser==2.22
Pygments==2.18.0
pyparsing==3.2.0
pyro-api==0.1.2
pyro-ppl==1.9.1
python-dateutil==2.9.0.post0
python-json-logger==2.0.7
pytz==2024.2
PyYAML==6.0.2
pyzmq==26.2.0
referencing==0.35.1
requests==2.32.3
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
rpds-py==0.21.0
scipy==1.14.1
Send2Trash==1.8.3
six==1.16.0
sniffio==1.3.1
soupsieve==2.6
stack-data==0.6.3
sympy==1.13.1
tables==3.10.1
terminado==0.18.1
tinycss2==1.4.0
tomli==2.1.0
torch==2.5.1
tornado==6.4.1
tqdm==4.67.0
traitlets==5.14.3
triton==3.1.0
types-python-dateutil==2.9.0.20241003
typing_extensions==4.12.2
tzdata==2024.2
uri-template==1.3.0
urllib3==2.2.3
wcwidth==0.2.13
webcolors==24.11.1
webencodings==0.5.1
websocket-client==1.8.0
widgetsnbextension==4.0.13
```

**Comment by christophista** [comment]
Hello

With the help of another issue and a reply therein that I oversaw yesterday [1] I was able to run CellBender. 
Please find here my changes: 

```
python -m venv ./cellbender_venv
./cellbender_venv/bin/python3 -m pip install 'torch==1.13.1'
./cellbender_venv/bin/python3 -m pip install 'cellbender==0.3.0'
``` 

Best regards, christoph

[1] https://github.com/broadinstitute/CellBender/issues/371#issuecomment-2282802094
