### ISSUE TITLE
Error during inference

### ISSUE THREAD

**Issue by cnk113** [broadinstitute/CellBender#49]
I'm getting a value error during the inference step.

```cellbender:remove-background: Trimming dataset for inference.
Traceback (most recent call last):
  File "/home/chang/miniconda3/envs/solo/bin/cellbender", line 11, in <module>
    load_entry_point('cellbender', 'console_scripts', 'cellbender')()
  File "/media/chang/HDD-3/chang/CellBender/cellbender/base_cli.py", line 101, in main
    cli_dict[args.tool].run(args)
  File "/media/chang/HDD-3/chang/CellBender/cellbender/remove_background/cli.py", line 92, in run
    main(args)
  File "/media/chang/HDD-3/chang/CellBender/cellbender/remove_background/cli.py", line 185, in main
    run_remove_background(args)
  File "/media/chang/HDD-3/chang/CellBender/cellbender/remove_background/cli.py", line 143, in run_remove_background
    args.low_count_threshold)
  File "/media/chang/HDD-3/chang/CellBender/cellbender/remove_background/data/dataset.py", line 90, in __init__
    gene_blacklist=gene_blacklist)
  File "/media/chang/HDD-3/chang/CellBender/cellbender/remove_background/data/dataset.py", line 205, in _trim_dataset_for_analysis
    get_d_priors_from_dataset(self)  # After gene trimming
  File "/media/chang/HDD-3/chang/CellBender/cellbender/remove_background/data/dataset.py", line 1057, in get_d_priors_from_dataset
    empty_counts = int(np.expm1(empty_log_counts).item())
ValueError: can only convert an array of size 1 to a Python scalar
```

**Comment by cnk113** [comment]
Different dataset from the same run:
```cellbender:remove-background: Trimming dataset for inference.
/home/chang/.local/lib/python3.6/site-packages/numpy/core/fromnumeric.py:3257: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/home/chang/.local/lib/python3.6/site-packages/numpy/core/_methods.py:161: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
Traceback (most recent call last):
  File "/home/chang/miniconda3/envs/solo/bin/cellbender", line 11, in <module>
    load_entry_point('cellbender', 'console_scripts', 'cellbender')()
  File "/media/chang/HDD-3/chang/CellBender/cellbender/base_cli.py", line 101, in main
    cli_dict[args.tool].run(args)
  File "/media/chang/HDD-3/chang/CellBender/cellbender/remove_background/cli.py", line 92, in run
    main(args)
  File "/media/chang/HDD-3/chang/CellBender/cellbender/remove_background/cli.py", line 185, in main
    run_remove_background(args)
  File "/media/chang/HDD-3/chang/CellBender/cellbender/remove_background/cli.py", line 143, in run_remove_background
    args.low_count_threshold)
  File "/media/chang/HDD-3/chang/CellBender/cellbender/remove_background/data/dataset.py", line 90, in __init__
    gene_blacklist=gene_blacklist)
  File "/media/chang/HDD-3/chang/CellBender/cellbender/remove_background/data/dataset.py", line 205, in _trim_dataset_for_analysis
    get_d_priors_from_dataset(self)  # After gene trimming
  File "/media/chang/HDD-3/chang/CellBender/cellbender/remove_background/data/dataset.py", line 1064, in get_d_priors_from_dataset
    cell_counts = int(np.expm1(cell_log_counts).item())
ValueError: cannot convert float NaN to integer
```

**Comment by sjfleming** [comment]
For some reason it seems that the algorithm is failing to find a region of the UMI curve that is "cells" and a region that is "empty droplets."  If you can paste a picture of the UMI curve, I might be able to suggest some settings that will give the algorithm enough hints so that it can succeed.

**Comment by mbabadi** [comment]
@cnk113 is your problem resolved?

**Comment by cnk113** [comment]
Yes.
