### ISSUE TITLE
Issue installing/running cellbender: No module named 'cellbender.remove_background'

### ISSUE THREAD

**Issue by jmchan88** [broadinstitute/CellBender#72]
Dear cellbender team!

I installed cellbender without error in a conda environment following the instructions, but when even trying to run any command with "cellbender," I get the following error below. I have tried running this on a server with GPUs. Any help would be greatly appreciated!

```
Traceback (most recent call last):
  File "/home/chanj3/anaconda3/envs/cellbender/bin/cellbender", line 8, in <module>
    sys.exit(main())
  File "/home/chanj3/anaconda3/envs/cellbender/lib/python3.7/site-packages/cellbender/base_cli.py", line 90, in main
    parser = get_populated_argparser()
  File "/home/chanj3/anaconda3/envs/cellbender/lib/python3.7/site-packages/cellbender/base_cli.py", line 76, in get_populated_argparser
    module_argparse = importlib.import_module('.'.join(module_argparse_str_list))
  File "/home/chanj3/anaconda3/envs/cellbender/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'cellbender.remove_background'
```

**Comment by sjfleming** [comment]
What happens if you type
```
cellbender -h
```
at the command line?

**Comment by jmchan88** [comment]
Same error message: 

```
(cellbender) [chanj3|lilac] ~ $ cellbender -h
Traceback (most recent call last):
  File "/home/chanj3/anaconda3/envs/cellbender/bin/cellbender", line 8, in <module>
    sys.exit(main())
  File "/home/chanj3/anaconda3/envs/cellbender/lib/python3.7/site-packages/cellbender/base_cli.py", line 90, in main
    parser = get_populated_argparser()
  File "/home/chanj3/anaconda3/envs/cellbender/lib/python3.7/site-packages/cellbender/base_cli.py", line 76, in get_populated_argparser
    module_argparse = importlib.import_module('.'.join(module_argparse_str_list))
  File "/home/chanj3/anaconda3/envs/cellbender/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'cellbender.remove_background'
```

**Comment by jmchan88** [comment]
Actually, in installing cellbender, I get the warnings:
```
awscli 1.18.19 requires colorama<0.4.4,>=0.2.5; python_version != "3.4", which is not installed.
awscli 1.18.19 requires PyYAML<5.4,>=3.10; python_version != "3.4", which is not installed.
botocore 1.15.19 requires docutils<0.16,>=0.10, but you'll have docutils 0.16 which is incompatible.
awscli 1.18.19 requires docutils<0.16,>=0.10, but you'll have docutils 0.16 which is incompatible.
```

Not sure if this is relevant ... because I already have aws installed. I don't know if cellbender is seeing aws though, or this could hint at the issue?

**Comment by jmchan88** [comment]
Ahh figured it out! I lied, I didn't follow the directions exactly. I ran

```
pip install git+https://github.com/broadinstitute/CellBender.git
```

rather than actually cloning the github repository directly. I figured that it was going to be the same thing, but I guess not! Thanks!

**Comment by sjfleming** [comment]
Glad you got it to work!
