### ISSUE TITLE
Error running cellbender

### ISSUE THREAD

**Issue by mxposed** [broadinstitute/CellBender#96]
Hello,

I'm installing cellbender like this: `pip install git+https://github.com/broadinstitute/CellBender.git@v0.2.0#egg=CellBender`

It installs successfully, however doesn't work afterward:

```
$ pipenv run cellbender --help
Traceback (most recent call last):
  File "/projects/b1038/Pulmonary/nmarkov/ssc-v2/code/.venv/bin/cellbender", line 8, in <module>
    sys.exit(main())
  File "/projects/b1038/Pulmonary/nmarkov/ssc-v2/code/.venv/lib/python3.7/site-packages/cellbender/base_cli.py", line 91, in main
    cli_dict = generate_cli_dictionary()
  File "/projects/b1038/Pulmonary/nmarkov/ssc-v2/code/.venv/lib/python3.7/site-packages/cellbender/base_cli.py", line 52, in generate_cli_dictionary
    module_cli = importlib.import_module('.'.join(module_cli_str_list))
  File "/software/python-anaconda3/2019.10/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/projects/b1038/Pulmonary/nmarkov/ssc-v2/code/.venv/lib/python3.7/site-packages/cellbender/remove_background/cli.py", line 4, in <module>
    from cellbender.remove_background.data.dataset import SingleCellRNACountsDataset
  File "/projects/b1038/Pulmonary/nmarkov/ssc-v2/code/.venv/lib/python3.7/site-packages/cellbender/remove_background/data/dataset.py", line 11, in <module>
    import cellbender.remove_background.model
  File "/projects/b1038/Pulmonary/nmarkov/ssc-v2/code/.venv/lib/python3.7/site-packages/cellbender/remove_background/model.py", line 9, in <module>
    import pyro
  File "/projects/b1038/Pulmonary/nmarkov/ssc-v2/code/.venv/lib/python3.7/site-packages/pyro/__init__.py", line 4, in <module>
    import pyro.poutine as poutine
  File "/projects/b1038/Pulmonary/nmarkov/ssc-v2/code/.venv/lib/python3.7/site-packages/pyro/poutine/__init__.py", line 4, in <module>
    from .handlers import (
  File "/projects/b1038/Pulmonary/nmarkov/ssc-v2/code/.venv/lib/python3.7/site-packages/pyro/poutine/handlers.py", line 60, in <module>
    from .collapse_messenger import CollapseMessenger
  File "/projects/b1038/Pulmonary/nmarkov/ssc-v2/code/.venv/lib/python3.7/site-packages/pyro/poutine/collapse_messenger.py", line 7, in <module>
    from pyro.distributions.distribution import COERCIONS
  File "/projects/b1038/Pulmonary/nmarkov/ssc-v2/code/.venv/lib/python3.7/site-packages/pyro/distributions/__init__.py", line 4, in <module>
    import pyro.distributions.torch_patch  # noqa F403
  File "/projects/b1038/Pulmonary/nmarkov/ssc-v2/code/.venv/lib/python3.7/site-packages/pyro/distributions/torch_patch.py", line 85, in <module>
    @patch_dependency('torch.distributions.constraints._CorrCholesky.check')
  File "/projects/b1038/Pulmonary/nmarkov/ssc-v2/code/.venv/lib/python3.7/site-packages/pyro/distributions/torch_patch.py", line 18, in patch_dependency
    module = getattr(module, part)
AttributeError: module 'torch.distributions.constraints' has no attribute '_CorrCholesky'
```

Maybe I need to fix `pyro` or `torch` dependency to some particular version?

**Comment by mxposed** [comment]
Sorry, had fixed torch 1.7 but new pyro 1.6. Fixed by downgrading pyro

**Comment by wmacnair** [comment]
Hey @mxposed, just in case you still have it, would you be able to share a yaml file for your conda env? I'm having trouble installing CellBender, and a list of package versions from a environment that works would be great 😅 

Thanks!
Will

**Comment by mxposed** [comment]
Sorry @wmacnair I don't use conda

**Comment by wmacnair** [comment]
Ok, thanks. I managed to get it to work in the end, by actually following the installation instructions and not trying to use a colleague's environment...
